export const products = [
    {
        name: "Uniswap",
        logo: "https://ph-files.imgix.net/3090d95b-e49a-497d-8a1c-38a2da573396.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=40&h=40&fit=crop&frame=1&dpr=2",
        description: "A decentralized trading protocol for cryptocurrencies.",
        category: "DeFi",
        blockchain: "Ethereum",
    },
    {
        name: "Aave",
        logo: "https://ph-files.imgix.net/67782944-2d34-4058-b46d-d64dd92c1f24.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=40&h=40&fit=crop&frame=1&dpr=2",
        description: "A decentralized finance protocol for lending and borrowing.",
        category: "DeFi",
        blockchain: "Ethereum",
    },
    {
        name: "Chainlink",
        logo: "https://ph-files.imgix.net/f624f746-226d-424b-80d6-3b5ade5bb7b2.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "A decentralized oracle network that connects smart contracts with real-world data.",
        category: "Oracle",
        blockchain: "Ethereum",
    },
    {
        name: "Polygon",
        logo: "https://ph-files.imgix.net/27ac1d24-0085-4c21-a314-26640ae636c7.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "A layer 2 scaling solution for Ethereum, providing faster and cheaper transactions.",
        category: "Layer 2",
        blockchain: "Ethereum",
    },
    {
        name: "SushiSwap",
        logo: "https://ph-avatars.imgix.net/4097455/1857fa34-a344-40fd-9bea-853d3f6c1618.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "A community-driven decentralized exchange and automated market-making platform.",
        category: "DeFi",
        blockchain: "Ethereum",
    },
    {
        name: "Uniswap",
        logo: "https://ph-files.imgix.net/3090d95b-e49a-497d-8a1c-38a2da573396.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=40&h=40&fit=crop&frame=1&dpr=2",
        description: "A decentralized trading protocol for cryptocurrencies.",
        category: "DeFi",
        blockchain: "Ethereum",
    },
    {
        name: "Filecoin",
        logo: "https://ph-files.imgix.net/03f6f216-02e1-4fc3-ad0b-1fac79f1f9d2.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "A decentralized storage network that allows users to rent out unused hard drive space.",
        category: "Storage",
        blockchain: "Filecoin",
    },
    {
        name: "Decentraland",
        logo: "https://ph-files.imgix.net/9f2409d4-efe4-40cd-b8de-2f1eec6834a4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "A virtual reality platform powered by the Ethereum blockchain where users can create, experience, and monetize content.",
        category: "Metaverse",
        blockchain: "Ethereum",
    },
    {
        name: "Compound",
        logo: "https://ph-files.imgix.net/cf2a4382-fbb6-4e93-9dd6-018805365cda.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "An algorithmic, autonomous interest rate protocol built for developers, to unlock a universe of open financial applications.",
        category: "DeFi",
        blockchain: "Ethereum",
    },
    {
        name: "OpenSea",
        logo: "https://ph-avatars.imgix.net/1184515/original.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "The largest marketplace for buying and selling NFTs (non-fungible tokens).",
        category: "NFT Marketplace",
        blockchain: "Ethereum, Polygon, Klaytn",
    },

    {
        name: "Aave",
        logo: "https://ph-files.imgix.net/67782944-2d34-4058-b46d-d64dd92c1f24.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=40&h=40&fit=crop&frame=1&dpr=2",
        description: "A decentralized finance protocol for lending and borrowing.",
        category: "DeFi",
        blockchain: "Ethereum",
    },
    {
        name: "Uniswap",
        logo: "https://ph-files.imgix.net/3090d95b-e49a-497d-8a1c-38a2da573396.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=40&h=40&fit=crop&frame=1&dpr=2",
        description: "A decentralized trading protocol for cryptocurrencies.",
        category: "DeFi",
        blockchain: "Ethereum",
    },

    {
        name: "Polygon",
        logo: "https://ph-files.imgix.net/27ac1d24-0085-4c21-a314-26640ae636c7.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "A layer 2 scaling solution for Ethereum, providing faster and cheaper transactions.",
        category: "Layer 2",
        blockchain: "Ethereum",
    },
    {
        name: "Chainlink",
        logo: "https://ph-files.imgix.net/f624f746-226d-424b-80d6-3b5ade5bb7b2.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "A decentralized oracle network that connects smart contracts with real-world data.",
        category: "Oracle",
        blockchain: "Ethereum",
    },

    {
        name: "Uniswap",
        logo: "https://ph-files.imgix.net/3090d95b-e49a-497d-8a1c-38a2da573396.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=40&h=40&fit=crop&frame=1&dpr=2",
        description: "A decentralized trading protocol for cryptocurrencies.",
        category: "DeFi",
        blockchain: "Ethereum",
    },
    {
        name: "SushiSwap",
        logo: "https://ph-avatars.imgix.net/4097455/1857fa34-a344-40fd-9bea-853d3f6c1618.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "A community-driven decentralized exchange and automated market-making platform.",
        category: "DeFi",
        blockchain: "Ethereum",
    },

    {
        name: "Decentraland",
        logo: "https://ph-files.imgix.net/9f2409d4-efe4-40cd-b8de-2f1eec6834a4.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "A virtual reality platform powered by the Ethereum blockchain where users can create, experience, and monetize content.",
        category: "Metaverse",
        blockchain: "Ethereum",
    },
    {
        name: "Filecoin",
        logo: "https://ph-files.imgix.net/03f6f216-02e1-4fc3-ad0b-1fac79f1f9d2.png?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "A decentralized storage network that allows users to rent out unused hard drive space.",
        category: "Storage",
        blockchain: "Filecoin",
    },

    {
        name: "OpenSea",
        logo: "https://ph-avatars.imgix.net/1184515/original.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "The largest marketplace for buying and selling NFTs (non-fungible tokens).",
        category: "NFT Marketplace",
        blockchain: "Ethereum, Polygon, Klaytn",
    },
    {
        name: "Compound",
        logo: "https://ph-files.imgix.net/cf2a4382-fbb6-4e93-9dd6-018805365cda.jpeg?auto=compress&codec=mozjpeg&cs=strip&auto=format&w=38&h=38&fit=crop&frame=1&dpr=2",
        description: "An algorithmic, autonomous interest rate protocol built for developers, to unlock a universe of open financial applications.",
        category: "DeFi",
        blockchain: "Ethereum",
    },
];